### ISSUE TITLE
Quick theme setting during loading

### ISSUE THREAD

**Issue by ArtemSBulgakov** [one-zero-eight/InNoHassle-Website#119]
Сейчас сайт открывается сначала в темной теме, а после рендера React меняет на нужную. Из-за этого первые N миллисекунд отображается не та тема.

**Comment by ArtemSBulgakov** [comment]
Material-UI для этого запускает свой код в теге script, который срабатывает до загрузки React

**Comment by evermake** [comment]
Nuxt has a plugin that uses color scheme setting from cookies, so correct theme is rendered on first request on the server. Can we do something similar?

**Comment by ArtemSBulgakov** [comment]
We use App router here, so it should work that way. But it needs testing with offline mode as Next will try to get a new layout on each request
