### ISSUE TITLE
События понедельника не отображаются в календаре дэшборда

### ISSUE THREAD

**Issue by danmaninc** [one-zero-eight/InNoHassle-Website#125]
Шаги воспроизведения:
1. Добавить в избранное любые календари, которые имеют события в понедельник
2. Открыть Dashboard, открыть вид календаря Month
3. События в понедельник не отображаются.

Эти события по каким-то причинам отображаются только на последней неделе семестра (май)
![image](https://github.com/one-zero-eight/InNoHassle-Website/assets/71718152/4eb1f8ee-620d-4d8f-97e4-3ff5f06be3cb)
![image](https://github.com/one-zero-eight/InNoHassle-Website/assets/71718152/6fe048ed-648c-4bc8-8d93-e07e6b2c9788)

**Comment by ArtemSBulgakov** [comment]
Same as #126.

Was fixed in https://github.com/one-zero-eight/InNoHassle-Website/commit/94e3fe93cf8aae6740dba9735db6b941c5d13eb6
