### ISSUE TITLE
Fix wrapping groups when >=2 cards in favorites in Dashboard

### ISSUE THREAD

**Issue by ArtemSBulgakov** [one-zero-eight/InNoHassle-Website#14]
![Image](https://user-images.githubusercontent.com/44732506/250259255-20f6e510-e622-4f9c-aeaa-3245523c7c3a.png)

![Image](https://user-images.githubusercontent.com/44732506/250259259-47b0f638-e15c-49d7-ac7f-0005e83855c0.png)

**Comment by danmaninc** [comment]
I have several solutions on my mind:

1. decrease the width of each GroupCard
2. make it responsive to the size of content

I stick to the second option right now. Do you have any other ideas?

**Comment by ArtemSBulgakov** [comment]
We can just set max-width of the columns



![Image](https://github.com/one-zero-eight/InNoHassle-Website/assets/44732506/6499ad3e-e659-415f-a4a8-9586330a6cab)


I've set 40% and 50% for them, so they don't wrap. But it also needs additional tuning for small screen sizes

**Comment by danmaninc** [comment]
This issue is fixed and will be closed by merging #29.
