### ISSUE TITLE
Make a button to hide/unhide groups from calendar in Dashboard

### ISSUE THREAD

**Issue by ArtemSBulgakov** [one-zero-eight/InNoHassle-Website#16]

**Comment by ArtemSBulgakov** [comment]
Commit https://github.com/one-zero-eight/InNoHassle-Website/commit/71c1cf5bf5fb0d4b6b33dd61e83ca909e729ce48 adds functionality to hide and unhide groups

**Comment by ArtemSBulgakov** [comment]
@danmaninc I used the same icon as for favorites. Please, replace it with some new icon

**Comment by danmaninc** [comment]
> @danmaninc I used the same icon as for favorites. Please, replace it with some new icon

Commit https://github.com/one-zero-eight/InNoHassle-Website/commit/9ab650f3542f8b007f0c79d243c7c5626d81ebf8 adds the new icon for this button.
