### ISSUE TITLE
Add user icon in Dashboard

### ISSUE THREAD

**Issue by ArtemSBulgakov** [one-zero-eight/InNoHassle-Website#19]
![Image](https://github.com/one-zero-eight/InNoHassle-Website/assets/71718152/47e73f3b-48d1-499c-806b-b1cab8e825b8)

**Comment by danmaninc** [comment]
Closed by https://github.com/one-zero-eight/InNoHassle-Website/commit/baf7c3a177d6f1a163dc9381bbbcfb90e6ab30cc
