### ISSUE TITLE
Fix small shifting due to disappearing of scrollbar

### ISSUE THREAD

**Issue by danmaninc** [one-zero-eight/InNoHassle-Website#20]
![Image](https://github.com/one-zero-eight/InNoHassle-Website/assets/71718152/91a01422-882e-4b8d-a4d6-2179cf8a79c5)

**Comment by ArtemSBulgakov** [comment]
Maybe use `overflow-y: scroll` on body, so scrollbar is always visible

**Comment by danmaninc** [comment]
This issue is fixed and will be closed by merging #29.

**Comment by danmaninc** [comment]
This issue appeared again, which is strange. Will look closer at this later.
![Image](https://github.com/one-zero-eight/InNoHassle-Website/assets/71718152/625f5cb6-7153-41c0-b965-9d4d71c7f019)
