### ISSUE TITLE
Sidebar does not reach the bottom of the page (mobile devices)

### ISSUE THREAD

**Issue by danmaninc** [one-zero-eight/InNoHassle-Website#30]
![Image](https://github.com/one-zero-eight/InNoHassle-Website/assets/71718152/8efbd521-8619-452c-994d-2093eccc78cc)

**Comment by ArtemSBulgakov** [comment]
Check this on real devices and different browsers. Currently sidebar uses 100dvh to fill the height which is supported by all browsers. It should work, so maybe you have bugs of developer tools in your browser.

**Comment by danmaninc** [comment]
Now I cannot reproduce this bug, so I believe that this is a problem of developer tools.
Anyway, this bug has appeared on specific size of screen. So on the most devices it should work correctly.
