### ISSUE TITLE
Second scrollbar appears when importing a calendar

### ISSUE THREAD

**Issue by danmaninc** [one-zero-eight/InNoHassle-Website#32]
![second](https://github.com/one-zero-eight/InNoHassle-Website/assets/71718152/51074e54-7ab5-4688-a2e1-33a622a6ac6e)

**Comment by ArtemSBulgakov** [comment]
I think this is because of https://github.com/one-zero-eight/InNoHassle-Website/pull/29/commits/8e47e869a079810d7f2d9b189db1fefc5476f0fb
