### ISSUE TITLE
Duplication of core courses events in the calendar view

### ISSUE THREAD

**Issue by danmaninc** [one-zero-eight/InNoHassle-Website#33]
If you add to the favorites several groups of the same year, you will get duplicating events in the calendar view.

![Image](https://github.com/one-zero-eight/InNoHassle-Website/assets/71718152/82b0bde2-f49c-4a3b-832d-234388c7e86e)
![Image](https://github.com/one-zero-eight/InNoHassle-Website/assets/71718152/3751a3ba-1dc4-4a29-a05a-63af9969ab54)

**Comment by danmaninc** [comment]
This [StackOverflow thread](https://stackoverflow.com/questions/34606866/fullcalendar-how-to-merge-two-events-that-are-next-to-each-other) may be somehow useful although it is mostly about nearby events.

I'm trying to find out is there any way to customize rendering of the calendar. 
I suppose that it is pretty small bug and easy-to-fix, however, only if it is possible to modify the way of displaying.

**However**, this issue may be _not planned_. 
If you import such calendars, events of core courses will overlap the same way and will not merge. Therefore, fixing the calendar view issue will be useless, since it will occur in calendar app.
So such «bug» may be fixed by creating custom EventGroup and adding events manually.

If I am correct about the possible solution (just allow users to create EventGroups), then this issue may be closed as not planned.

What do you think about this issue? @ArtemSBulgakov

**Comment by ArtemSBulgakov** [comment]
That SO thread is about creating events, it's not our case.

In our repository we include a modified version of iCalendarPlugin that adds events from .ics file. I think we can make the plugin take multiple files as input (currently plugin just runs several times for multiple urls) and adds only unique events (comparing them by UID).
