### ISSUE TITLE
Add more features to the user icon

### ISSUE THREAD

**Issue by danmaninc** [one-zero-eight/InNoHassle-Website#37]
- [x] Add the «View Profile» button
- [ ] Add the icons for the buttons
![image](https://github.com/one-zero-eight/InNoHassle-Website/assets/71718152/b8f34703-aa31-47bb-aeaf-0386680b0b4c)

**Comment by ArtemSBulgakov** [comment]
That's how it looks now:

![Image](https://github.com/one-zero-eight/InNoHassle-Website/assets/44732506/8626edb6-8bd1-40d9-982b-10a739a02719)

**Comment by danmaninc** [comment]
Now it looks like this:
![image](https://github.com/one-zero-eight/InNoHassle-Website/assets/71718152/02829437-7a7c-4af6-ba32-02149f2f5372)
