### ISSUE TITLE
Add sports schedule support

### ISSUE THREAD

**Issue by dantetemplar** [one-zero-eight/InNoHassle-Website#4]
Requires [parser for sport schedule](https://github.com/orgs/one-zero-eight/projects/4/views/1?pane=issue&itemId=31319430)

**Comment by danmaninc** [comment]
Sports schedule already supported by the website. If you add the new category in API, website will automatically add new category card with corresponding schedule.

I see the only tasks for this — creating designed EventGroup with images (may be the new issue) and corresponding pages (#34). What do you think?
