### ISSUE TITLE
Fix inconsistent padding for the menu button

### ISSUE THREAD

**Issue by danmaninc** [one-zero-eight/InNoHassle-Website#42]
![image](https://github.com/one-zero-eight/InNoHassle-Website/assets/71718152/d2f5722b-510b-438e-83e5-ca5995ca575e)

**Comment by danmaninc** [comment]
Now I'm thinking that it is normal behavior. I do not really understand how it would be better to position this button.
If I will make margin of text and menu button, it would be strange.

![Image](https://github.com/one-zero-eight/InNoHassle-Website/assets/71718152/1d6e91e2-5c95-44a8-91e8-28aa239380d3)

So I'm about to leave it as it is, since it does not really affect user experience.
![Image](https://github.com/one-zero-eight/InNoHassle-Website/assets/71718152/9b232625-592d-447b-9346-b86dadd58f31)


But also I would open an issue to add background for this menu button. I want to know your opinion, @ArtemSBulgakov

**Comment by ArtemSBulgakov** [comment]
I think it's ok without background
