### ISSUE TITLE
Add the loading state

### ISSUE THREAD

**Issue by danmaninc** [one-zero-eight/InNoHassle-Website#49]
- [x] Prevent appearing all ScheduleElements being «favorited» while loading user data.
- [ ] Add loading state to remove the 2-3 seconds delay between user click (sidebar) and dashboard appearance.

![Image](https://user-images.githubusercontent.com/71718152/250261504-1a9f30ae-1f22-435a-954e-fbb7db717375.gif)

**Comment by ArtemSBulgakov** [comment]
1. Should be fixed by #e0b1fdfe
