### ISSUE TITLE
Add the images for the sport schedule in the list

### ISSUE THREAD

**Issue by danmaninc** [one-zero-eight/InNoHassle-Website#65]
Add the images for each sport schedule in the schedule search.
Requires #4 & Requires image support by the API.
For now, since we do not have images, there will be only placeholder at this moment.

**Comment by danmaninc** [comment]
However, this issue may be closed as not planned, since we do not have any unique images for each group.
Moreover, adding the same image for multiple sport clubs is not very good idea in my opinion.
Maybe, we should use generator in case we will add the images.

What do you think?

**Comment by ArtemSBulgakov** [comment]
We can move this issue to backlog till images are supported by API

**Comment by danmaninc** [comment]
This issue will be closed as not planned until the images will be supported by the API.

When the support will be available, this issue should be re-opened.
