### ISSUE TITLE
View components of event group

### ISSUE THREAD

**Issue by dantetemplar** [one-zero-eight/InNoHassle-Website#79]
Select an additional view for event-group

![Image](https://github.com/one-zero-eight/InNoHassle-Website/assets/69670642/13722535-c8c3-454c-8f07-e3534c371b4b)

With listing of event-group structure: other event-groups that are included in the current one; added and excluded events.

![Image](https://github.com/one-zero-eight/InNoHassle-Website/assets/69670642/fdbe3129-5b24-4021-9097-e0a95e928ee0)

**Comment by danmaninc** [comment]
I've done a little sketch in Figma project. Currently it is not sufficiently detailed.
Also, I've left some comments with questions, that require some answer. However, I will continue detalization without them at this moment.

I'm looking forward for the response in these comments.
![image](https://github.com/one-zero-eight/InNoHassle-Website/assets/71718152/e698dc3c-09db-4c2a-afc0-b2172a1a39fc)
