### ISSUE TITLE
Auto deploy to dev server

### ISSUE THREAD

**Issue by ArtemSBulgakov** [one-zero-eight/InNoHassle-Website#87]

**Comment by dantetemplar** [comment]
@ArtemSBulgakov Good job

**Comment by ArtemSBulgakov** [comment]
Auto deployment to staging server is done in https://github.com/one-zero-eight/InNoHassle-Website/commit/7d4b8e8e1355740bc1f47b279702fa517a334237

Deployment to production server is done in https://github.com/one-zero-eight/InNoHassle-Website/commit/c89c29351608fb5e285543a87a1d52b5b16a3e3b
